# conf/task/train.yaml

name: 'train'

basic:
  batch_size:   16
  num_workers:  28
  num_epochs:   5000
  loss:         CrossEntropyLoss
  metric:       'mIoU'                    # ['mIoU', 'Dice', 'PACC']

hyper:
  optimizer:
    learning_rate:  1e-5
    beta1:          0.9
    beta2:          0.999
  scheduler:
    mode:           'min'
    factor:         0.8
    patience:       5
  amp:
    enabled:        true